# Initially from https://gist.github.com/LukeMathWalker/5ae1107432ce283310c3e601fac915f3
name: Docker

on: 
  push:
    branches: 
      - master
    tags:
      - v*

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Modify scripts and get version
      id: version
      uses: actions/github-script@v6
      with:
        script: |
          core.setOutput('sha_version', `${context.ref.slice(context.ref.lastIndexOf("/") + 1)}-${context.sha}`);

          if (context.ref.startsWith("refs/tags/v")) {
            core.setOutput('latest', 'latest');
            core.setOutput('version', context.ref.slice(context.ref.lastIndexOf("/v") + 2));
          } else {
            const date = new Date();
            const year = date.getUTCFullYear();
            const month = `${date.getUTCMonth()+1}`.padStart(2, '0');
            const day = `${date.getUTCDate()}`.padStart(2, '0');
            const hour = `${date.getUTCHours()}`.padStart(2, '0');
            const minute = `${date.getUTCMinutes()}`.padStart(2, '0');
            const d = `${year}-${month}-${day}T${hour}-${minute}`;

            core.setOutput('latest', 'nightly');
            core.setOutput('version', `nightly-${d}-${context.sha.substring(0, 7)}`);
          }

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Docker Registry login
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push
    - name: Build a multi-platform docker image and push (for master)
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          ghcr.io/mpthlee/sharers:nightly
          ghcr.io/mpthlee/sharers:latest
        cache-to: |
          type=inline
          type=local,dest=/tmp/.buildx-cache-new,mode=max
        build-args: BUILD_VER=${{ steps.version.outputs.version }}
        load: false
        no-cache: ${{ contains(github.event.head_commit.message, '[no cache]') }}
        push: ${{ github.repository_owner == 'MPThLee' }}
        tags: |
          ghcr.io/mpthlee/sharers:${{ steps.version.outputs.latest }}
          ghcr.io/mpthlee/sharers:${{ steps.version.outputs.sha_version }}
          ghcr.io/mpthlee/sharers:${{ steps.version.outputs.version }}

    - # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
